### PR TITLE
fix image path

### PR DESCRIPTION
**Pull request by acelan86**
修复css中图片相对路径问题

### CODE REVIEW

**Comment by MoOx** [comment]
postcss-url can do that :p

**Comment by acelan86** [comment]
well, seems a better way  : )
try~

**Comment by yisibl** [comment]
postcss-url +1.

@MoOx 
BTW
I want to get online image size, what method is there?

```
background: url(https://pbs.twimg.com/profile_images/3139131054/03bacd00078aeeffb04a755c2471f857_bigger.jpeg)
```

**Comment by MoOx** [comment]
Also checkout https://github.com/borodean/postcss-assets

**Pull request merged**
